In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = '/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/MaSaC_train_erc.json'

In [ ]:
import pandas as pd
test1 = pd.read_json(file_path)
df = pd.DataFrame(test1)
df

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,"[maya, indu, rosesh, indu, maya, indu, rosesh,...",[kya kya bhar ke rakha hai indravadan ne is gh...,"[disgust, contempt, anger, neutral, neutral, c..."
1,roseshantstobeadopted.wmv,"[maya, rosesh, indu, rosesh, maya, maya, indu,...","[rosesh beta happy diwali!, you bet momma., ro...","[joy, neutral, joy, sadness, neutral, joy, neu..."
2,roseshantstobeadopted.wmv,"[maya, indu, maya, indu, maya, maya, indu, may...","[radha bai! vitthal! monisha!, maya suno, ye k...","[neutral, fear, disgust, neutral, contempt, ne..."
3,roseshantstobeadopted.wmv,"[sahil, monisha, sahil, monisha, sahil, monish...","[rosesh chup ho jao. monisha pani lekar aao!, ...","[anger, neutral, neutral, neutral, neutral, ne..."
4,roseshantstobeadopted.wmv,"[rosesh, maya, rosesh, maya, rosesh, maya, ros...","[momma aap mujhse dur hi rahe to behtar hoga, ...","[sadness, neutral, contempt, neutral, sadness,..."
...,...,...,...,...
338,radhabaileaves,"[sahil, radha bai, vitthal, radha bai, sahil, ...",[radha bhai radha bhai please aap rona band ki...,"[neutral, sadness, sadness, sadness, neutral, ..."
339,radhabaileaves,"[maya, indu, rosesh, indu, maya, indu, maya, i...","[indravadan! rosesh ka play hit ho gaya!, achc...","[joy, joy, neutral, neutral, neutral, joy, joy..."
340,radhabaileaves,"[maya, monish, maya, sahil, maya, sahil, monis...",[monisha tumne un logon ko bhadkake acha nahin...,"[anger, neutral, neutral, neutral, contempt, a..."
341,radhabaileaves,"[ila ben, maya, indu, ila ben, indu, maya, ila...","[maya ye hai sita aur geeta, ye akeli hi seeta...","[neutral, surprise, joy, neutral, joy, neutral..."
342,radhabaileaves,"[sahil, indu, sahil, indu, sahil, indu, sahil,...","[dad, ye kya kar rhe hai aap?, anti-bai spray ...","[surprise, neutral, neutral, disgust, joy, dis..."

In [ ]:
len(df['speakers'][1])

38

In [ ]:
newDF = pd.DataFrame(columns = ['episode', 'speakers', 'utterances', 'emotions'])

for col in ['speakers', 'utterances', 'emotions']:
    i=0
    for row in range(len(df)):
        tempList = df.iloc[row][col]
        episodeName = df.iloc[row]['episode']
        for e in tempList:
            newDF.at[i, col] = e
            newDF.at[i, 'episode'] = episodeName
            i = i + 1

In [ ]:
newDF

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral
...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger
8503,radhabaileaves,maya,ahan!,joy
8504,radhabaileaves,sita or geeta,goodbye!,fear
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust

In [ ]:
newDF.to_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/task1Input.csv", index=False)

In [ ]:
task1CSV = pd.read_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/task1Input.csv")
task1DF = pd.DataFrame(task1CSV)
task1DF

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral
...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger
8503,radhabaileaves,maya,ahan!,joy
8504,radhabaileaves,sita or geeta,goodbye!,fear
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust

In [ ]:
task1DF.columns

Index(['episode', 'speakers', 'utterances', 'emotions'], dtype='object')

In [ ]:
tast1DF['emotions'].unique()