In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = '/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/task1Input.csv'

In [ ]:
import pandas as pd
df = pd.read_csv(file_path)
df

,episode,speakers,utterances,emotions
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral
...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger
8503,radhabaileaves,maya,ahan!,joy
8504,radhabaileaves,sita or geeta,goodbye!,fear
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):
    # Lowercasing: Convert text to lowercase
    text = text.lower()

    # Tokenization: Split the text into words
    words = nltk.word_tokenize(text)

    # Remove punctuation and non-alphanumeric characters
    words = [word for word in words if re.match(r'^[a-z]+$', word)]

    # Remove English stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    # Lemmatization: Reduce words to their base form
    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]

    # Join the words back into a single string
    preprocessed_text = ' '.join(words)

    return preprocessed_text

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [ ]:
df['cleaned_utterances'] = df['utterances'].apply(preprocess_text)
df

,episode,speakers,utterances,emotions,cleaned_utterances
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust,kya kya bhar ke rakha hai indravadan ne ghar m...
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt,ok chalo rosesh chalo bahar
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger,momma hath chhodiye dad
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral,dekho maya ya na bol raha hai fir tum hi kahog...
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral,indravadan tum kitne salo se ye joke maar rahe...
...,...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness,lekin ghadi ki ghadi hai momma recurring alarm...
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger,nhi nhi mujhe yahan pe kaamich nhi karna hai j...
8503,radhabaileaves,maya,ahan!,joy,ahan
8504,radhabaileaves,sita or geeta,goodbye!,fear,goodbye
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust,goodbye nikalo nikalo chorro hath chorro badby...

In [ ]:
#Import libraries
# import matplotlib.pyplot as plt
# from wordcloud import WordCloud

#Generate word cloud
# total_text = " ".join(df.cleaned_utterances.tolist())
# wc = WordCloud(width=400, height=330, max_words=100, background_color='white').generate_from_text(total_text)
# plt.figure(figsize=(12, 8))
# plt.imshow(wc, interpolation='bilinear')
# plt.axis('off')
# plt.show()

In [ ]:
!pip install indic_transliteration

Collecting indic_transliteration
  Downloading indic_transliteration-2.3.53-py3-none-any.whl (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.1/146.1 kB 3.0 MB/s eta 0:00:00
Collecting backports.functools-lru-cache (from indic_transliteration)
  Downloading backports.functools_lru_cache-1.6.6-py2.py3-none-any.whl (5.9 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.10/dist-packages (from indic_transliteration) (2023.6.3)
Requirement already satisfied: typer in /usr/local/lib/python3.10/dist-packages (from indic_transliteration) (0.9.0)
Requirement already satisfied: toml in /usr/local/lib/python3.10/dist-packages (from indic_transliteration) (0.10.2)
Collecting roman (from indic_transliteration)
  Downloading roman-4.1-py3-none-any.whl (5.5 kB)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer->indic_transliteration) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from typer->indic_transliteration) (4.5.0)
Installing collected packages: roman, backports.functools-lru-cache, indic_transliteration
Successfully installed backports.functools-lru-cache-1.6.6 indic_transliteration-2.3.53 roman-4.1

In [ ]:
from indic_transliteration import sanscript

# Function to transliterate English text to Hindi
def transliterate_to_hindi(text):
    # Specify the source and target scripts
    source_script = sanscript.ITRANS
    target_script = sanscript.DEVANAGARI

    # Transliterate the text
    transliterated_text = sanscript.transliterate(text, source_script, target_script)
    return transliterated_text

In [ ]:
df['hindi_utterances'] = df['utterances'].apply(transliterate_to_hindi)

In [ ]:
df

,episode,speakers,utterances,emotions,cleaned_utterances,hindi_utterances
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust,kya kya bhar ke rakha hai indravadan ne ghar m...,क्य क्य भर् के रख है इन्द्रवदन् ने इस् घर् मेइ...
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt,ok chalo rosesh chalo bahar,"ओक्, चलो रोसेश् चलो बहर्"
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger,momma hath chhodiye dad,मोम्म! हथ् छोदिये दद्!
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral,dekho maya ya na bol raha hai fir tum hi kahog...,देखो मय य न बोल् रह है! फ़िर् तुम् हि कहोगि फ़ल्...
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral,indravadan tum kitne salo se ye joke maar rahe...,"इन्द्रवदन्, तुम् कित्ने सलो से ये जोके मार् रह..."
...,...,...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness,lekin ghadi ki ghadi hai momma recurring alarm...,लेकिन् व्हत् अबोउत् म्य् घदि? १७००० कि घदि है ...
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger,nhi nhi mujhe yahan pe kaamich nhi karna hai j...,"न्हि न्हि मुझे यहन् पे कामिच् न्हि कर्न है, मे..."
8503,radhabaileaves,maya,ahan!,joy,ahan,अहन्!
8504,radhabaileaves,sita or geeta,goodbye!,fear,goodbye,गूद्ब्ये!
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust,goodbye nikalo nikalo chorro hath chorro badby...,"नो गूद्ब्ये! निकलो! निकलो! चोर्रो हथ् चोर्रो, ..."

In [2]:
!pip install mtranslate

Collecting mtranslate
  Downloading mtranslate-1.8.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mtranslate
  Building wheel for mtranslate (setup.py) ... done
  Created wheel for mtranslate: filename=mtranslate-1.8-py3-none-any.whl size=3672 sha256=fdb738f45496c8b078a3608e62a4eb9d9968e335c4240ecddf51bfa0167f00c1
  Stored in directory: /root/.cache/pip/wheels/c2/04/15/d7654c2c4a9a52e09922967593f3278fed66059be65ca671ea
Successfully built mtranslate
Installing collected packages: mtranslate
Successfully installed mtranslate-1.8

In [3]:
from mtranslate import translate

def translate_to_english(text):
  english_translation = translate(text, 'en', 'hi')

  return english_translation

In [ ]:
df['english_utterances'] = None

In [ ]:
df['english_utterances'][:1000] = df['utterances'][:1000].apply(translate_to_english)
df

,episode,speakers,utterances,emotions,cleaned_utterances,hindi_utterances,english_utterances
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust,kya kya bhar ke rakha hai indravadan ne ghar m...,क्य क्य भर् के रख है इन्द्रवदन् ने इस् घर् मेइ...,What does Indravadan keep in the house? Indrav...
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt,ok chalo rosesh chalo bahar,"ओक्, चलो रोसेश् चलो बहर्","ok, let's rise, let's spring"
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger,momma hath chhodiye dad,मोम्म! हथ् छोदिये दद्!,Momma! Hath Chodiye Dad!
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral,dekho maya ya na bol raha hai fir tum hi kahog...,देखो मय य न बोल् रह है! फ़िर् तुम् हि कहोगि फ़ल्...,Look Maya or I am not speaking! Then you will ...
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral,indravadan tum kitne salo se ye joke maar rahe...,"इन्द्रवदन्, तुम् कित्ने सलो से ये जोके मार् रह...","Indravadan, for how many years have you been t..."
...,...,...,...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness,lekin ghadi ki ghadi hai momma recurring alarm...,लेकिन् व्हत् अबोउत् म्य् घदि? १७००० कि घदि है ...,None
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger,nhi nhi mujhe yahan pe kaamich nhi karna hai j...,"न्हि न्हि मुझे यहन् पे कामिच् न्हि कर्न है, मे...",None
8503,radhabaileaves,maya,ahan!,joy,ahan,अहन्!,None
8504,radhabaileaves,sita or geeta,goodbye!,fear,goodbye,गूद्ब्ये!,None
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust,goodbye nikalo nikalo chorro hath chorro badby...,"नो गूद्ब्ये! निकलो! निकलो! चोर्रो हथ् चोर्रो, ...",None

In [ ]:
df['english_utterances'][1000:2000] = df['utterances'][1000:2000].apply(translate_to_english)

In [ ]:
df['english_utterances'][2000:3000] = df['utterances'][2000:3000].apply(translate_to_english)

In [ ]:
df.to_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/preprocessedInput.csv", index=False)

In [4]:
import pandas as pd
df2 = pd.read_csv('/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/preprocessedInput.csv')
df2

,episode,speakers,utterances,emotions,cleaned_utterances,hindi_utterances,english_utterances
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust,kya kya bhar ke rakha hai indravadan ne ghar m...,क्य क्य भर् के रख है इन्द्रवदन् ने इस् घर् मेइ...,What does Indravadan keep in the house? Indrav...
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt,ok chalo rosesh chalo bahar,"ओक्, चलो रोसेश् चलो बहर्","ok, let's rise, let's spring"
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger,momma hath chhodiye dad,मोम्म! हथ् छोदिये दद्!,Momma! Hath Chodiye Dad!
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral,dekho maya ya na bol raha hai fir tum hi kahog...,देखो मय य न बोल् रह है! फ़िर् तुम् हि कहोगि फ़ल्...,Look Maya or I am not speaking! Then you will ...
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral,indravadan tum kitne salo se ye joke maar rahe...,"इन्द्रवदन्, तुम् कित्ने सलो से ये जोके मार् रह...","Indravadan, for how many years have you been t..."
...,...,...,...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness,lekin ghadi ki ghadi hai momma recurring alarm...,लेकिन् व्हत् अबोउत् म्य् घदि? १७००० कि घदि है ...,NaN
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger,nhi nhi mujhe yahan pe kaamich nhi karna hai j...,"न्हि न्हि मुझे यहन् पे कामिच् न्हि कर्न है, मे...",NaN
8503,radhabaileaves,maya,ahan!,joy,ahan,अहन्!,NaN
8504,radhabaileaves,sita or geeta,goodbye!,fear,goodbye,गूद्ब्ये!,NaN
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust,goodbye nikalo nikalo chorro hath chorro badby...,"नो गूद्ब्ये! निकलो! निकलो! चोर्रो हथ् चोर्रो, ...",NaN

In [6]:
df2['english_utterances'][3000:4000] = df2['utterances'][3000:4000].apply(translate_to_english)

In [7]:
df2['english_utterances'][4000:5000] = df2['utterances'][4000:5000].apply(translate_to_english)

In [8]:
df2['english_utterances'][5000:6000] = df2['utterances'][5000:6000].apply(translate_to_english)

In [9]:
df2['english_utterances'][6000:7000] = df2['utterances'][6000:7000].apply(translate_to_english)

In [10]:
df2['english_utterances'][7000:8000] = df2['utterances'][7000:8000].apply(translate_to_english)

In [11]:
df2['english_utterances'][8000:] = df2['utterances'][8000:].apply(translate_to_english)

In [12]:
df2

,episode,speakers,utterances,emotions,cleaned_utterances,hindi_utterances,english_utterances
0,roseshantstobeadopted.wmv,maya,kya kya bhar ke rakha hai indravadan ne is gha...,disgust,kya kya bhar ke rakha hai indravadan ne ghar m...,क्य क्य भर् के रख है इन्द्रवदन् ने इस् घर् मेइ...,What does Indravadan keep in the house? Indrav...
1,roseshantstobeadopted.wmv,indu,"ok, chalo rosesh chalo bahar",contempt,ok chalo rosesh chalo bahar,"ओक्, चलो रोसेश् चलो बहर्","ok, let's rise, let's spring"
2,roseshantstobeadopted.wmv,rosesh,momma! hath chhodiye dad!,anger,momma hath chhodiye dad,मोम्म! हथ् छोदिये दद्!,Momma! Hath Chodiye Dad!
3,roseshantstobeadopted.wmv,indu,dekho maya ya na bol raha hai! fir tum hi kaho...,neutral,dekho maya ya na bol raha hai fir tum hi kahog...,देखो मय य न बोल् रह है! फ़िर् तुम् हि कहोगि फ़ल्...,Look Maya or I am not speaking! Then you will ...
4,roseshantstobeadopted.wmv,maya,"indravadan, tum kitne salo se ye joke maar rah...",neutral,indravadan tum kitne salo se ye joke maar rahe...,"इन्द्रवदन्, तुम् कित्ने सलो से ये जोके मार् रह...","Indravadan, for how many years have you been t..."
...,...,...,...,...,...,...,...
8501,radhabaileaves,rosesh,lekin what about my ghadi? 17000 ki ghadi hai ...,sadness,lekin ghadi ki ghadi hai momma recurring alarm...,लेकिन् व्हत् अबोउत् म्य् घदि? १७००० कि घदि है ...,but what about my Ghadi? 17000 ki ghadi hai mo...
8502,radhabaileaves,sita or geeta,"nhi nhi mujhe yahan pe kaamich nhi karna hai, ...",anger,nhi nhi mujhe yahan pe kaamich nhi karna hai j...,"न्हि न्हि मुझे यहन् पे कामिच् न्हि कर्न है, मे...","No no, I don't want to do evil here, I am here!"
8503,radhabaileaves,maya,ahan!,joy,ahan,अहन्!,oh!
8504,radhabaileaves,sita or geeta,goodbye!,fear,goodbye,गूद्ब्ये!,goodbye!
8505,radhabaileaves,maya,no goodbye! nikalo! nikalo! chorro hath chorro...,disgust,goodbye nikalo nikalo chorro hath chorro badby...,"नो गूद्ब्ये! निकलो! निकलो! चोर्रो हथ् चोर्रो, ...",no goodbye! take it out! take it out! chorro h...

In [14]:
df2.to_csv("/content/drive/MyDrive/Minor-Project/ERC-EFR/Codebase/preprocessedInput.csv", index=False)